### ISSUE TITLE
MiniO installation Failure for existing EKS cluster

### ISSUE THREAD

**Issue by ashujain2** [minio/marketplace#2]
We subscribed to MinIO from the AWS Marketplace and trying to install MinIO for the existing EKS cluster as per usage instructions 
**https://github.com/minio/marketplace/blob/master/eks/existing-eks-cli-simple.md**

Step1- itself is not working - 

1.- Install the MinIO Operator with the AWS Integration
The following command will install the MinIO Operator with just kubectl.
**kubectl apply -k github.com/miniohq/marketplace/eks/resources** 

**_Shows Below error:-_** 

error: rawResources failed to read Resources: Load from path github.com/minio/operator/resources/?ref=v4.4.13 failed: evalsymlink failure on '/tmp/kustomize-383031607/eks/resources/github.com/minio/operator/resources/?ref=v4.4.13' : lstat /tmp/kustomize-383031607/eks/resources/github.com: no such file or directory

**Comment by AirbornePorcine** [comment]
We're also experiencing this problem which is preventing us from installing Minio.

**Comment by dvaldivia** [comment]
I'm not able to replicate the problem, do you have connectivity to the repository?

**Comment by pjuarezd** [comment]
Please refer to the install instuctions on https://min.io/product/multicloud-elastic-kubernetes-service/deploy instead.

Althoug we could not reproduce the issue at the moment, newer releases of Minio on Marketplace could have fixed the problem, see latest available release of MinIO Object Storage for `AWS EKS Server Container Offer` on [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-smchi7bcs4nn4)

And feel free to reach out in this repo for any issue, as well on https://subnet.min.io/ since your Marketplace subscription provides access to 24x7x365 subnet support.

**Comment by milo157** [comment]
This seems to still not be fixed. Following the commands above I get the same issue as @ashujain2 

`kubectl apply -k github.com/miniohq/marketplace/eks/resources                                                                                                       
`
`error: accumulating resources: accumulation err='accumulating resources from 'github.com/minio/operator/resources/?ref=v5.0.10': evalsymlink failure on '/private/var/folders/16/4tzfzzm521s4fws9pcjs78ym0000gn/T/kustomize-824210206/eks/resources/github.com/minio/operator/resources/?ref=v5.0.10' : lstat /private/var/folders/16/4tzfzzm521s4fws9pcjs78ym0000gn/T/kustomize-824210206/eks/resources/github.com: no such file or directory': hit 27s timeout running '/usr/bin/git fetch --depth=1 origin v5.0.10'`
